name: compass
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - numpy>=1.20
  - gdal>=3.3
  - isce3
  - libgdal-netcdf
  - libgdal-hdf5
  - pandas>=1.4
  - pillow>=7.0
  - pyproj>=3.3
  - pysolid>=0.3
  - ruamel.yaml>=0.15
  - scipy>=1.0,<1.13
  - yamale>=4.0
  - h5py>=3.5
  - shapely>=1.8
  - requests>=2.0
  - scikit-image
  - lxml
# CI unit test
  - pytest
  - pluggy
  - pytest-order
# Dependencies for RAiDER
  - progressbar
  - rasterio
  - dem_stitcher
  - gxx_linux-64>=9,<10
